In [1]:
import matplotlib.pyplot as plt
import pandas as pd
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout, Bidirectional
from keras.models import load_model
import numpy as np
import getWeather


In [2]:
dataset = pd.read_csv('models/weatherHistory.csv')
final_summary = pd.DataFrame(dataset)
unique_values = final_summary.Summary.unique()
final_summary.Summary = pd.Categorical(final_summary.Summary)
final_summary['summary_code'] = final_summary.Summary
final_summary['Summary'] = final_summary.Summary.cat.codes
final_precip_type = pd.DataFrame(dataset)
unique_values_precip_types = final_precip_type['Precip Type'].unique()
final_precip_type['Precip Type'] = pd.Categorical(final_precip_type['Precip Type'])
final_precip_type['precip_type'] = final_precip_type['Precip Type']
final_precip_type['Precip Type'] = final_precip_type['Precip Type'].cat.codes
tempreature_training_set = final_precip_type.iloc[:,1:11]



In [4]:
tempreature_training_set = np.array(tempreature_training_set)
days = tempreature_training_set[:, 0:11]
ModelWeather = getWeather.ModelsPredict(days , [])
tempreature = ModelWeather.PredictTempreture()
print(tempreature)

[[8.88419  8.982492 9.003601 8.879715 8.66197 ]]


In [7]:
tempreature_training_set = np.array(tempreature_training_set)
days = tempreature_training_set[:, 0:11]
ModelWeather = getWeather.ModelsPredict(days , [])
humidity = ModelWeather.predictHumidity()
print(humidity)

[[0.81367993 0.8254775  0.8328848  0.83860844 0.84506416]]


In [8]:
tempreature_training_set = np.array(tempreature_training_set)
days = tempreature_training_set[:, 0:11]
ModelWeather = getWeather.ModelsPredict(days , [])
loadCover = ModelWeather.predictLoadCover()
print(loadCover)

[[0. 0. 0. 0. 0.]]


In [16]:
tempreature_training_set = np.array(tempreature_training_set)
days = tempreature_training_set[: , 0:11]
ModelWeather = getWeather.ModelsPredict(days , [])
wind = ModelWeather.predictWind()
print(wind)

[[ 9.895529  9.024424  9.62767  10.938923 11.077234]]


In [10]:
summaryarray =  [[0] * 4 for i in range(5)]
for i in range (5):
  summaryarray[i][0] = tempreature [0][i]
  summaryarray[i][1] = humidity [0][i]
  summaryarray[i][2] = wind  [0][i]
  summaryarray[i][3] = loadCover [0][i]
print(summaryarray)

[[8.88419, 0.81367993, 11.399976, 0.0], [8.982492, 0.8254775, 11.080125, 0.0], [9.003601, 0.8328848, 10.657753, 0.0], [8.879715, 0.83860844, 9.507294, 0.0], [8.66197, 0.84506416, 8.765035, 0.0]]


In [11]:
import pickle
summaryArray = np.array(summaryarray)
summary_model = pickle.load(open('models/summary.h5', 'rb'))
summaryResult = summary_model.predict(summaryArray)
print(summaryResult)

['Partly Cloudy' 'Mostly Cloudy' 'Mostly Cloudy' 'Mostly Cloudy'
 'Overcast']


array(['Mostly Cloudy', 'Overcast', 'Overcast', 'Partly Cloudy',
       'Mostly Cloudy'], dtype=object)